# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_name', models.CharField(max_length=20, primary_key='Ture', serialize=False)),
                ('area_url', models.CharField(blank='Ture', max_length=100, null='Ture')),
                ('area_account', models.CharField(blank='Ture', max_length=50, null='Ture')),
                ('area_password', models.CharField(blank='Ture', max_length=50, null='Ture')),
                ('area_description', models.CharField(blank='Ture', max_length=200, null='Ture')),
            ],
        ),
    ]
