# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0002_group_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_name',
            field=models.CharField(max_length=100),
        ),
    ]
