# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0003_auto_20160721_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='group_id',
            new_name='group',
        ),
        migrations.AddField(
            model_name='host',
            name='area',
            field=models.ForeignKey(default='staging', on_delete=django.db.models.deletion.CASCADE, to='Assets.Area'),
            preserve_default=False,
        ),
    ]
