# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0005_auto_20160721_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='servers_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_mem', models.CharField(max_length=12)),
                ('v_mem', models.CharField(max_length=16)),
                ('cpu_models', models.CharField(max_length=16)),
                ('cpu_count', models.CharField(max_length=16)),
                ('system_type', models.CharField(max_length=16)),
                ('disk_total', models.CharField(max_length=16)),
                ('kernel_version', models.CharField(max_length=16)),
                ('update_time', models.DateTimeField(verbose_name='last update time')),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='host_nip',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='servers_info',
            name='host_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assets.Host', to_field='host_nip'),
        ),
    ]
