# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0007_auto_20160722_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers_info',
            name='cpu_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servers_info',
            name='disk_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servers_info',
            name='p_mem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servers_info',
            name='v_mem',
            field=models.IntegerField(),
        ),
    ]
