# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0010_servers_info_host_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWS_INSTANCES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_tags', models.CharField(blank='Ture', max_length=100, null='Ture')),
                ('instance_type', models.CharField(max_length=48)),
                ('instance_id', models.CharField(max_length=48)),
                ('instance_private_ip', models.CharField(max_length=48)),
                ('instance_public_ip', models.CharField(max_length=48)),
                ('instance_state', models.CharField(max_length=48)),
                ('instance_create_time', models.DateTimeField(verbose_name='instance create time')),
            ],
        ),
    ]
