# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0011_aws_instances'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_access_key',
            field=models.CharField(blank='Ture', max_length=100, null='Ture'),
        ),
        migrations.AddField(
            model_name='area',
            name='area_privte_key',
            field=models.CharField(blank='Ture', max_length=100, null='Ture'),
        ),
        migrations.AddField(
            model_name='area',
            name='area_region',
            field=models.CharField(blank='Ture', max_length=50, null='Ture'),
        ),
        migrations.AddField(
            model_name='aws_instances',
            name='instance_area',
            field=models.ForeignKey(default='staging', on_delete=django.db.models.deletion.CASCADE, to='Assets.Area'),
            preserve_default=False,
        ),
    ]
