# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0012_auto_20160811_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area_privte_key',
            new_name='area_private_key',
        ),
    ]
