# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salt_info',
            name='description',
            field=models.CharField(blank='Ture', max_length=200, null='Ture'),
        ),
        migrations.AddField(
            model_name='salt_info',
            name='name',
            field=models.CharField(max_length=16, null='Ture'),
        ),
    ]
