# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salt', '0002_auto_20160608_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salt_info',
            old_name='password',
            new_name='salt_api_account',
        ),
        migrations.RenameField(
            model_name='salt_info',
            old_name='name',
            new_name='salt_api_name',
        ),
        migrations.RenameField(
            model_name='salt_info',
            old_name='user',
            new_name='salt_api_password',
        ),
        migrations.RenameField(
            model_name='salt_info',
            old_name='url',
            new_name='salt_api_url',
        ),
    ]
