# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salt', '0005_auto_20160722_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salt_info',
            old_name='salt_api_password1',
            new_name='salt_api_account',
        ),
    ]
