# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salt', '0006_auto_20160722_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=100, verbose_name='Salt\u547d\u4ee4')),
                ('doc', models.TextField(blank=True, max_length=1000, verbose_name='\u5e2e\u52a9\u6587\u6863')),
            ],
            options={
                'verbose_name': 'Salt\u547d\u4ee4',
                'verbose_name_plural': 'Salt\u547d\u4ee4\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default=b'execution', max_length=20, verbose_name='Salt\u6a21\u5757\u7c7b\u578b')),
                ('name', models.CharField(max_length=20, verbose_name='Salt\u6a21\u5757\u540d\u79f0')),
            ],
            options={
                'verbose_name': 'Salt\u6a21\u5757',
                'verbose_name_plural': 'Salt\u6a21\u5757\u5217\u8868',
            },
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([('client', 'name')]),
        ),
        migrations.AddField(
            model_name='command',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salt.Module', verbose_name='\u6240\u5c5e\u6a21\u5757'),
        ),
        migrations.AlterUniqueTogether(
            name='command',
            unique_together=set([('module', 'cmd')]),
        ),
    ]
