# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salt', '0007_auto_20160804_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salt_info',
            options={'verbose_name': 'Salt_info\u5e10\u53f7\u4fe1\u606f', 'verbose_name_plural': 'Salt API\u767b\u5f55\u4fe1\u606f'},
        ),
        migrations.AlterUniqueTogether(
            name='command',
            unique_together=set([]),
        ),
    ]
